#!/usr/bin/env python
import socket
import sys
port = 3700
if (len(sys.argv) == 3):
    hostname = sys.argv[1]
    NUID = (sys.argv[2])
elif (len(sys.argv) == 4):
    port = int(sys.argv[1])
    hostname = sys.argv[2]
    NUID = (sys.argv[3])
else: 
    print "Invalid number of arguments"
    exit()


if not isinstance(port, int) or not isinstance(NUID, str):
    print "Invalid arguments"
    exit()


# Create an INET, STREAMing socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Now conncet to the web server on port 3700
# login-faculty.ccs.neu.edu

s.connect((hostname, port))

key = 1
data = s.recv(64)
if (data == "HELLO\n"):
    #print data
    s.send("IAM " + str(NUID) + "\n")
    data = s.recv(64)

    while key == 1:     
        while not data.endswith('\n'):
            data += s.recv(64)
        #print data
        list = data.split("\n")
        for element in list:
            #if contains "KEY" then get KEY
            if "KEY" in element:
                key = element.split(" ")[1]
            #if contains "INFO" then get INFO
            if "INFO" in element:
                challenge = element.split(" ")[1]
                #print "REPLY " + str(challenge)
                s.send("REPLY " + str(challenge) + "\n" )
                data = s.recv(64)
                #print data
    print key

s.close()
exit()        
         

